import os
import json
import re
import logging
from fastapi import APIRouter, Depends, HTTPException, Body
from starlette.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from db import get_db
from app.core.prompts import ONBOARDING_ARCHITECT_PROMPT
from app.core.credentials import get_tenant_credential_by_type
import openai

router = APIRouter()
logger = logging.getLogger(__name__)


def _get_platform_key_sync() -> str:
    """Resolve OpenAI API key synchronously. Called at import time."""
    # Direct env read — most reliable
    key = os.getenv("OPENAI_API_KEY")
    if key:
        return key
    try:
        from app.core.config import settings as app_settings
        if app_settings.OPENAI_API_KEY:
            return app_settings.OPENAI_API_KEY
    except Exception:
        pass
    return ""

# Cache the key at module load time
_CACHED_PLATFORM_KEY = _get_platform_key_sync()
logger.info(f"Platform key loaded: {'YES' if _CACHED_PLATFORM_KEY else 'NO'} (len={len(_CACHED_PLATFORM_KEY)})")


async def _get_platform_key(tenant_id: int = 0) -> str:
    """Resolve OpenAI API key."""
    global _CACHED_PLATFORM_KEY

    # Use cached key (loaded at startup)
    if _CACHED_PLATFORM_KEY:
        return _CACHED_PLATFORM_KEY

    # Try tenant credential from DB
    if tenant_id:
        try:
            key = await get_tenant_credential_by_type(tenant_id, "OPENAI_API_KEY")
            if key:
                return key
        except Exception:
            pass

    # Re-read env (in case it was set after startup)
    key = os.getenv("OPENAI_API_KEY")
    if key:
        _CACHED_PLATFORM_KEY = key
        return key

    raise HTTPException(status_code=500, detail="Platform API key not configured")

# Memory Store (In-Memory for now, ideally Redis)
# Format: { "session_id": [ {"role": "system", ...}, {"role": "user", ...} ] }
ONBOARDING_SESSIONS = {}

@router.post("/interview")
async def onboarding_interview(
    session_id: str = Body(..., embed=True),
    user_message: str = Body(..., embed=True),
    tenant_id: int = Body(..., embed=True),
    reset: bool = Body(False, embed=True),
    db: AsyncSession = Depends(get_db)
):
    """
    Handles the turn-by-turn interview with the AI Architect.
    """
    try:
        # 1. Initialize Session
        if reset or session_id not in ONBOARDING_SESSIONS:
            ONBOARDING_SESSIONS[session_id] = [
                {"role": "system", "content": ONBOARDING_ARCHITECT_PROMPT}
            ]
            # Initial greeting is generated by AI, so we trigger empty run if reset
            if reset:
                 user_message = "Hola, quiero crear mi agente."

        # Nexus v7.6.1 Security Audit: Onboarding Usage Limits (P3 Remediation)
        # Enforce 5 free interviews per tenant, then require API key configuration
        from db import redis_client
        
        onboarding_key = f"onboarding:interviews:{tenant_id}"
        interview_count = await redis_client.incr(onboarding_key)
        
        # Set 30-day TTL on first use
        if interview_count == 1:
            await redis_client.expire(onboarding_key, 30 * 24 * 60 * 60)  # 30 days in seconds
        
        # Check limit (5 interviews max before requiring own API key)
        if interview_count > 5:
            remaining_ttl = await redis_client.ttl(onboarding_key)
            days_remaining = max(0, remaining_ttl // (24 * 60 * 60))
            
            logger.warning("onboarding_limit_exceeded", extra={"tenant_id": tenant_id, "count": interview_count})
            
            return {
                "error": "Onboarding Limit Reached",
                "detail": f"Has utilizado tus 5 entrevistas gratuitas. Para continuar creando agentes, configura tu propia API Key de OpenAI en el Credential Vault. El límite se reiniciará en {days_remaining} días.",
                "action_required": "configure_api_key",
                "limit_reset_days": days_remaining,
                "ai_message": "🔒 **Límite Alcanzado**: Has completado tus 5 entrevistas de prueba. Para continuar, ve a **Configuración → Credenciales** y agrega tu OpenAI API Key."
            }

        # 2. Append User Message
        ONBOARDING_SESSIONS[session_id].append({"role": "user", "content": user_message})

        # 3. Get Credentials — platform key (company pays for onboarding)
        api_key = await _get_platform_key(tenant_id)
        client = openai.AsyncOpenAI(api_key=api_key)

        # 4. Generate AI Response
        response = await client.chat.completions.create(
            model="gpt-4o",
            messages=ONBOARDING_SESSIONS[session_id],
            temperature=0.7
        )

        ai_text = response.choices[0].message.content
        ONBOARDING_SESSIONS[session_id].append({"role": "assistant", "content": ai_text})

        # 5. Check for <CONFIG_READY> (Regex Robustness)
        import re
        config_ready = False
        extracted_data = None
        
        # Pattern to find anything between <CONFIG_READY> tags, ignoring case and multi-line
        pattern = re.compile(r"<CONFIG_READY>(.*?)</CONFIG_READY>", re.DOTALL | re.IGNORECASE)
        match = pattern.search(ai_text)

        if match:
            config_ready = True
            try:
                json_str = match.group(1).strip()
                
                # Robustness: Remove markdown code blocks if present (```json or ```)
                json_str = re.sub(r"```(?:json)?\n?|\n?```", "", json_str).strip()
                
                extracted_data = json.loads(json_str)
                
                # Clean the response for the UI (remove the whole block)
                ai_text = pattern.sub("", ai_text).strip()
            except Exception as e:
                logger.error(f"JSON Parsing Error in Onboarding: {e}")
                config_ready = False

        return {
            "ai_message": ai_text,
            "config_ready": config_ready,
            "extracted_data": extracted_data
        }

    except Exception as e:
        logger.error(f"Onboarding Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/generate")
async def onboarding_generate(
    tenant_id: int = Body(..., embed=True),
    final_config: dict = Body(..., embed=True),
    db: AsyncSession = Depends(get_db)
):
    """
    Finalizes the onboarding: Creates the agent in the DB.
    """
    # Use the extracted data to create a 'Sales' agent
    from sqlalchemy import text
    # 1. Prepare JSON Config
    wizard_config = {
        "store_name": final_config.get("agent_name", "Nuevo Agente"),
        "business_description": final_config.get("store_description", ""),
        "agent_tone": final_config.get("agent_tone", ""),
        "business_rules": final_config.get("business_rules", ""),
        "synonym_dictionary": final_config.get("synonym_dictionary", ""),
        "website_url": final_config.get("store_website", ""),
        "store_address": final_config.get("store_address", ""),
        "shipping_partners": final_config.get("shipping_partners", ""),
        "catalog_knowledge": final_config.get("catalog_knowledge", ""),
        "template_type": "sales",
    }

    # 2. Insert into DB
    # We follow the same pattern as get_or_create_sales_agent but forcing a new one
    q_insert = text("""
        INSERT INTO agents (name, role, tenant_id, config, model_provider, model_version, is_active, enabled_tools, system_prompt_template, template_type)
        VALUES (:name, :role, :tenant_id, :config :: jsonb, :provider, :version, :is_active, :tools :: jsonb, :prompt, :template_type)
        RETURNING id
    """)

    try:
        result = await db.execute(q_insert, {
            "name": final_config.get("agent_name", "Agente IA"),
            "role": "sales", # Default role for Hyper-Onboarding
            "tenant_id": tenant_id,
            "config": json.dumps(wizard_config),
            "provider": "openai",
            "version": "gpt-4o",
            "is_active": True,
            "tools": json.dumps(["search_specific_products", "search_by_category", "browse_general_storefront", "orders", "derivhumano"]), # Standard Suite
            "prompt": "Eres un asistente virtual de ventas.", # Pivot: Placeholder prompt to satisfy NotNull constraint. Wizard will overwrite.
            "template_type": "sales"
        })
        await db.commit()
        new_id = result.scalar()
        
        return {"agent_id": new_id, "status": "created"}
        
    except Exception as e:
        logger.error(f"Failed to create agent via Onboarding: {e}")
        raise HTTPException(status_code=500, detail=str(e))
@router.post("/draft")
async def onboarding_draft(
    tenant_id: int = Body(..., embed=True),
    final_config: dict = Body(..., embed=True),
    db: AsyncSession = Depends(get_db)
):
    """
    Saves the Architect's output as a DRAFT agent (is_active=False).
    Returns draft_id for the Wizard to hydrate.
    """
    from sqlalchemy import text
    import json
    
    # 1. Prepare Wizard Config
    wizard_config = {
        "store_name": final_config.get("agent_name", "Nuevo Agente (Borrador)"),
        "business_description": final_config.get("store_description", ""),
        "agent_tone": final_config.get("agent_tone", ""),
        "business_rules": final_config.get("business_rules", ""),
        "synonym_dictionary": final_config.get("synonym_dictionary", ""),
        "website_url": final_config.get("store_website", ""),
        "store_address": final_config.get("store_address", ""),
        "shipping_partners": final_config.get("shipping_partners", ""),
        "catalog_knowledge": final_config.get("catalog_knowledge", ""),
        "template_type": "sales",
    }

    # 2. Insert into DB as INACTIVE
    q_insert = text("""
        INSERT INTO agents (name, role, tenant_id, config, model_provider, model_version, is_active, enabled_tools, system_prompt_template, template_type)
        VALUES (:name, :role, :tenant_id, :config :: jsonb, :provider, :version, :is_active, :tools :: jsonb, :prompt, :template_type)
        RETURNING id
    """)

    try:
        result = await db.execute(q_insert, {
            "name": f"[DRAFT] {final_config.get('agent_name', 'Agente')}", 
            "role": "sales", 
            "tenant_id": tenant_id,
            "config": json.dumps(wizard_config),
            "provider": "openai",
            "version": "gpt-4o",
            "is_active": False, # <--- DRAFT MODE
            "tools": json.dumps(["search_specific_products", "search_by_category", "browse_general_storefront", "orders", "derivhumano"]),
            "prompt": "[DRAFT] Pendiente de generacion.", # Pivot: Placeholder for draft
            "template_type": "sales"
        })
        await db.commit()
        draft_id = result.scalar()
        
        return {"draft_id": draft_id, "status": "draft_saved"}
        
    except Exception as e:
        logger.error(f"Failed to save draft: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# --- Wizard Interview Step (Section-Scoped Chat) ---

WIZARD_STEP_SESSIONS = {}

WIZARD_STEP_PROMPTS = {
    3: """Sos la Arquitecta de Identidad. Sos argentina, calida, profesional. Usas voseo natural.

FORMATO DE VOZ: Tus respuestas se reproducen como audio. Reglas estrictas:
- Texto plano conversacional. NUNCA uses markdown, asteriscos, listas con guiones, ni formatos.
- NO uses emojis. Hablas, no escribis.
- Maximo 3-4 oraciones por respuesta.
- Pregunta UNA cosa por vez. Espera la respuesta.
- Cuando el usuario responda algo corto o vago, pedi que se explaye. Necesitas detalles ricos.

TU MISION: Extraer la IDENTIDAD PROFUNDA del negocio. No es un formulario, es una entrevista inmersiva. Necesitas que el usuario se explaye 3-4 minutos contando su historia, sus clientes, su diferencial. Hacele preguntas que lo obliguen a pensar profundo.

FLUJO (segui este orden estricto):

1. CLIENTE IDEAL Y NEGOCIO:
   Arranca con: "Hola! Soy tu arquitecta de IA. Vamos a crear juntos la personalidad perfecta de tu agente. Empecemos por lo mas importante: contame sobre tu negocio. Como se llama, que venden, y sobre todo, quien es tu cliente ideal? Necesito que me pintes el cuadro completo, como si me estuvieras presentando tu tienda a un inversor."

   Si la respuesta es corta, insisti: "Necesito mas detalles. Que tipo de persona compra tus productos? Que edad tienen? Son mas mujeres o varones? Que buscan cuando entran a tu tienda, practicidad, precio, exclusividad? Contame una historia de un cliente tipico."

   Pedi tambien: "Que te hace diferente de tu competencia? Si alguien te pregunta por que comprar en tu tienda y no en otra, que le dirias?"

   Cuando tengas nombre + rubro + cliente ideal + diferencial detallado, emiti: <CONFIRM:identidad>
   Y decile: "Excelente, ya tengo claro quien sos y a quien le vendes. Ahora definamos como habla tu agente."

2. TONO Y PERSONALIDAD:
   Pregunta: "Imaginemos que entra un cliente a tu tienda. Lo recibis con un 'Hola, en que puedo ayudarte?' formal, o mas bien con un 'Ey, que buscas?' tipo barrio? Tratamos a los clientes de vos, de tu, o de usted?"

   Profundiza: "Y si un cliente esta indeciso entre dos productos, como lo guiarias? Sos de los que dice 'Mira, este te va a quedar espectacular' o mas bien 'Le recomiendo este modelo'? Dame un ejemplo de como le hablarias."

   Cuando tengas pronombres + formalidad + ejemplos concretos, emiti: <CONFIRM:tono>
   Decile: "Perfecto, ya tengo el tono. Ahora el estilo de comunicacion."

3. ESTILO DE COMUNICACION:
   Pregunta: "Usas emojis cuando hablas con clientes por WhatsApp? Cuales? Y hay alguna frase o muletilla que uses mucho? Por ejemplo, 'Dale', 'Genial', 'Miraa', 'Barbaro'... Esas frases que te salen naturales."

   Tambien: "Hay palabras o frases que JAMAS usarias con un cliente? Cosas que suenan falsas, de telemarketing, o que simplemente no van con tu marca?"

   Cuando tengas, emiti: <CONFIRM:estilo>
   Decile: "Listo el estilo. Una pregunta mas importante."

4. LIMITES Y RESTRICCIONES:
   Pregunta: "Que cosas tu agente NUNCA deberia decir o prometer? Por ejemplo, garantizar stock que no sabes si tenes, dar descuentos sin autorizacion, hablar de precios de la competencia... Que te daria panico que tu agente diga?"

   Cuando tengas, emiti: <CONFIRM:restricciones>

5. Genera el resumen completo adaptado al negocio y emiti:
   <SECTION_COMPLETE>{"section": "tone", "draft": "## TONO Y PERSONALIDAD\\n..."}</SECTION_COMPLETE>
   Decile: "Increible, ya arme la identidad completa de tu agente. Esta parte es clave y quedo muy bien."

REGLA DE ORO: Si el usuario da respuestas cortas de una oracion, SIEMPRE pedi mas detalles. Necesitas profundidad para generar un prompt de calidad. Usa preguntas con escenarios: "Imaginate que..." "Si un cliente te dice..." "Contame un caso real de...".""",

    4: """Sos la Arquitecta de Reglas. Sos argentina, calida, profesional. Usas voseo.

FORMATO DE VOZ: Texto plano, sin markdown ni emojis. Maximo 3-4 oraciones. Pregunta UNA cosa por vez.

TU MISION: Extraer las REGLAS OPERATIVAS reales del negocio. No queres respuestas genericas, queres las reglas de oro que hacen funcionar el negocio. Usa escenarios reales para forzar respuestas concretas.

FLUJO ESTRICTO:

1. ENVIOS Y LOGISTICA:
   "Ahora vamos con las reglas de tu negocio. Empecemos por envios. Hacen envios a domicilio? Son gratis o cobran? Desde que monto es gratis si hay un minimo? Cuanto tardan en llegar?"

   Profundiza: "Y si un cliente de otra provincia te pide envio, que le decis? Trabajan con alguna transportadora en particular? Correo Argentino, Andreani, Mercado Envios?"

   Cuando tengas, emiti: <CONFIRM:envios>
   Decile: "Envios configurados. Ahora una parte sensible: cambios y devoluciones."

2. CAMBIOS Y DEVOLUCIONES:
   Usa escenario: "Imaginemos esto: un cliente compro unas zapatillas, se las probo en la casa, y te escribe que no le gustaron y quiere devolverlas. Que le respondemos? Aceptamos? Tiene plazo?"

   Profundiza: "Y si alguien quiere cambiar ropa interior o traje de bano? Hay productos que no tienen cambio por higiene? Que pasa con productos en oferta o liquidacion?"

   Cuando tengas, emiti: <CONFIRM:cambios>
   Decile: "Perfecto. Ahora la parte operativa."

3. HORARIOS, PAGOS Y PROCESO:
   "Cual es tu horario de atencion? Y fuera de horario, el agente responde igual o avisa que van a contestar en horario comercial?"

   "Que formas de pago aceptan? MercadoPago, tarjeta, transferencia, efectivo? Hacen cuotas? Tienen algun descuento por pago en efectivo o transferencia?"

   "Y cuando un cliente quiere comprar, como es el proceso? Le mandas un link de pago, lo derivas a la web, toma el pedido por chat?"

   Cuando tengas, emiti: <CONFIRM:operativa>
   Decile: "Genial. Ultima pregunta clave."

4. PROHIBICIONES:
   "Que cosas el agente NO debe hacer NUNCA? Pensalo asi: que te haria perder un cliente o meterte en un problema? Por ejemplo: prometer entrega en menos de 24 horas si no podes cumplir, dar descuentos sin que vos lo autorices, inventar que hay stock de algo..."

   Cuando tengas, emiti: <CONFIRM:prohibiciones>

5. Genera reglas como imperativos claros y emiti:
   <SECTION_COMPLETE>{"section": "rules", "draft": "## REGLAS DE NEGOCIO\\n1. ENVIOS: ...\\n2. CAMBIOS Y DEVOLUCIONES: ...\\n3. HORARIOS: ...\\n4. FORMAS DE PAGO: ...\\n5. PROCESO DE COMPRA: ...\\n6. PROHIBICIONES: ..."}</SECTION_COMPLETE>
   Decile: "Reglas configuradas. Tu agente ya sabe exactamente que puede y que no puede hacer."

REGLA: Convierte respuestas vagas en reglas concretas e imperativas. Si dice "somos flexibles con los cambios", pregunta: "Flexible como? 7 dias? 30 dias? Solo con ticket? Sin uso?".""",

    5: """Sos la Arquitecta de Diccionario. Sos argentina, calida, profesional. Usas voseo.

FORMATO DE VOZ: Texto plano, sin markdown ni emojis. Maximo 3-4 oraciones. Pregunta UNA cosa por vez.

TU MISION: Mapear el LENGUAJE REAL que usan los clientes. Los clientes no hablan como un catalogo, usan jerga, abreviaciones, errores de ortografia, y nombres alternativos. Tu agente necesita entender todo eso.

FLUJO:

1. PRODUCTOS Y CATEGORIAS:
   "Ahora la ultima seccion: el diccionario. Esto es clave para que tu agente entienda a tus clientes. Contame: tus clientes le dicen diferente a tus productos? Por ejemplo, en ropa le dicen 'remera' o 'playera'? 'Zapatillas' o 'tenis'? 'Buzo' o 'sudadera'?"

   Profundiza: "Y las categorias? Le dicen 'ropa de entrecasa' o 'homewear'? 'Pilcha' o 'outfit'? Dame todos los sinonimos que se te ocurran de tus productos principales."

   Cuando tengas, emiti: <CONFIRM:categorias>
   Decile: "Genial. Ahora la jerga y las abreviaciones."

2. JERGA Y ABREVIACIONES:
   "Tus clientes usan abreviaciones en WhatsApp? Por ejemplo, 'Merca' por MercadoPago, 'transf' por transferencia, 'depto' por departamento, 'celu' por celular... Dame todas las que se te ocurran."

   "Y hay expresiones tipicas de tu zona o sector? Argentinismos, modismos, formas de preguntar precio como 'cuanto sale?' o 'que valor tiene?'?"

   "Tambien pensemos en errores de ortografia comunes. Tus clientes escriben 'aver' en vez de 'a ver'? 'Cuanto bale?' con b? El agente tiene que entender eso."

   Cuando tengas, emiti: <CONFIRM:jerga>

3. Genera tabla de sinonimos completa y emiti:
   <SECTION_COMPLETE>{"section": "dictionary", "draft": "## DICCIONARIO DE SINONIMOS Y JERGA\\n\\n### Productos\\nCATEGORIA_REAL: sinonimo1, sinonimo2\\n\\n### Abreviaciones\\nPALABRA_REAL: abreviacion1, abreviacion2\\n\\n### Errores comunes\\nCORRECTO: error_comun1, error_comun2"}</SECTION_COMPLETE>
   Decile: "Diccionario armado. Tu agente ya va a entender el lenguaje real de tus clientes, incluyendo la jerga y los errores de ortografia. Esto marca la diferencia."

REGLA: Si el usuario dice que no tiene sinonimos, insisti con ejemplos concretos de su sector. Siempre hay jerga que el negocio no nota porque la usa todos los dias."""
}


@router.post("/interview-step")
async def onboarding_interview_step(
    session_id: str = Body(..., embed=True),
    user_message: str = Body(..., embed=True),
    step: int = Body(..., embed=True),
    tenant_id: int = Body(0, embed=True),
    reset: bool = Body(False, embed=True),
    chat_history: list = Body([], embed=True),
):
    """
    Section-scoped interview for wizard steps 3, 4, 5.
    Each step uses a different prompt focused on that section.
    Accepts chat_history to re-seed context when user returns after closing.
    """
    if step not in WIZARD_STEP_PROMPTS:
        raise HTTPException(status_code=400, detail=f"Invalid step {step}. Must be 3, 4, or 5.")

    try:
        # Initialize or reset session
        step_session_key = f"{session_id}_step{step}"
        if reset or step_session_key not in WIZARD_STEP_SESSIONS:
            WIZARD_STEP_SESSIONS[step_session_key] = [
                {"role": "system", "content": WIZARD_STEP_PROMPTS[step]}
            ]

            # Re-seed with chat history if user is returning
            if chat_history and len(chat_history) > 0:
                for msg in chat_history:
                    role = msg.get("role", "user")
                    content = msg.get("content", "")
                    if role in ("user", "assistant") and content:
                        WIZARD_STEP_SESSIONS[step_session_key].append({"role": role, "content": content})
                # Tell the AI to continue where it left off
                user_message = "Retome la conversacion donde la dejamos. Que falta por configurar de esta seccion?"
            elif reset:
                user_message = "Hola, estoy listo para configurar esta seccion."

        # Append user message
        WIZARD_STEP_SESSIONS[step_session_key].append({"role": "user", "content": user_message})

        # Use platform API key (company pays for onboarding)
        api_key = await _get_platform_key(tenant_id)
        client = openai.AsyncOpenAI(api_key=api_key)

        response = await client.chat.completions.create(
            model="gpt-4o",
            messages=WIZARD_STEP_SESSIONS[step_session_key],
            temperature=0.7
        )

        ai_text = response.choices[0].message.content
        WIZARD_STEP_SESSIONS[step_session_key].append({"role": "assistant", "content": ai_text})

        # Check for CONFIRM tags (sub-section confirmations)
        confirm_section = None
        confirm_pattern = re.compile(r"<CONFIRM:(\w+)>", re.IGNORECASE)
        confirm_match = confirm_pattern.search(ai_text)
        if confirm_match:
            confirm_section = confirm_match.group(1)
            ai_text = confirm_pattern.sub("", ai_text).strip()

        # Check for SECTION_COMPLETE (full section done)
        section_complete = False
        extracted_draft = None

        pattern = re.compile(r"<SECTION_COMPLETE>(.*?)</SECTION_COMPLETE>", re.DOTALL | re.IGNORECASE)
        match = pattern.search(ai_text)

        if match:
            section_complete = True
            try:
                json_str = re.sub(r"```(?:json)?\n?|\n?```", "", match.group(1).strip()).strip()
                data = json.loads(json_str)
                extracted_draft = data.get("draft", "")
                ai_text = pattern.sub("", ai_text).strip()
            except Exception as e:
                logger.error(f"Section complete parse error: {e}")
                section_complete = False

        return {
            "ai_message": ai_text,
            "section_complete": section_complete,
            "extracted_draft": extracted_draft,
            "confirm_section": confirm_section,
            "step": step
        }

    except Exception as e:
        logger.error(f"Interview step error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# --- TTS Endpoint (Voice Architect) ---

@router.post("/tts")
async def onboarding_tts(text: str = Body(..., embed=True)):
    """Convert text to speech using OpenAI TTS. Returns MP3 audio bytes.
    Uses platform API key (company investment in onboarding UX).
    Voice: nova (femenina, cálida, ideal para LATAM).
    """
    try:
        api_key = await _get_platform_key()
        client = openai.AsyncOpenAI(api_key=api_key)

        response = await client.audio.speech.create(
            model="tts-1",
            voice="nova",
            input=text,
            response_format="mp3"
        )

        # Read full audio content
        audio_bytes = response.read()

        from fastapi.responses import Response
        return Response(content=audio_bytes, media_type="audio/mpeg")

    except Exception as e:
        logger.error(f"TTS error: {e}")
        raise HTTPException(status_code=500, detail=str(e))
