import os
import json
import re
import logging
from fastapi import APIRouter, Depends, HTTPException, Body
from starlette.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from db import get_db
from app.core.prompts import ONBOARDING_ARCHITECT_PROMPT
from app.core.credentials import get_tenant_credential_by_type
import openai

router = APIRouter()
logger = logging.getLogger(__name__)


def _get_platform_key_sync() -> str:
    """Resolve OpenAI API key synchronously. Called at import time."""
    # Direct env read — most reliable
    key = os.getenv("OPENAI_API_KEY")
    if key:
        return key
    try:
        from app.core.config import settings as app_settings
        if app_settings.OPENAI_API_KEY:
            return app_settings.OPENAI_API_KEY
    except Exception:
        pass
    return ""

# Cache the key at module load time
_CACHED_PLATFORM_KEY = _get_platform_key_sync()
logger.info(f"Platform key loaded: {'YES' if _CACHED_PLATFORM_KEY else 'NO'} (len={len(_CACHED_PLATFORM_KEY)})")


async def _get_platform_key(tenant_id: int = 0) -> str:
    """Resolve OpenAI API key."""
    global _CACHED_PLATFORM_KEY

    # Use cached key (loaded at startup)
    if _CACHED_PLATFORM_KEY:
        return _CACHED_PLATFORM_KEY

    # Try tenant credential from DB
    if tenant_id:
        try:
            key = await get_tenant_credential_by_type(tenant_id, "OPENAI_API_KEY")
            if key:
                return key
        except Exception:
            pass

    # Re-read env (in case it was set after startup)
    key = os.getenv("OPENAI_API_KEY")
    if key:
        _CACHED_PLATFORM_KEY = key
        return key

    raise HTTPException(status_code=500, detail="Platform API key not configured")

# Memory Store (In-Memory for now, ideally Redis)
# Format: { "session_id": [ {"role": "system", ...}, {"role": "user", ...} ] }
ONBOARDING_SESSIONS = {}

@router.post("/interview")
async def onboarding_interview(
    session_id: str = Body(..., embed=True),
    user_message: str = Body(..., embed=True),
    tenant_id: int = Body(..., embed=True),
    reset: bool = Body(False, embed=True),
    db: AsyncSession = Depends(get_db)
):
    """
    Handles the turn-by-turn interview with the AI Architect.
    """
    try:
        # 1. Initialize Session
        if reset or session_id not in ONBOARDING_SESSIONS:
            ONBOARDING_SESSIONS[session_id] = [
                {"role": "system", "content": ONBOARDING_ARCHITECT_PROMPT}
            ]
            # Initial greeting is generated by AI, so we trigger empty run if reset
            if reset:
                 user_message = "Hola, quiero crear mi agente."

        # Nexus v7.6.1 Security Audit: Onboarding Usage Limits (P3 Remediation)
        # Enforce 5 free interviews per tenant, then require API key configuration
        from db import redis_client
        
        onboarding_key = f"onboarding:interviews:{tenant_id}"
        interview_count = await redis_client.incr(onboarding_key)
        
        # Set 30-day TTL on first use
        if interview_count == 1:
            await redis_client.expire(onboarding_key, 30 * 24 * 60 * 60)  # 30 days in seconds
        
        # Check limit (5 interviews max before requiring own API key)
        if interview_count > 5:
            remaining_ttl = await redis_client.ttl(onboarding_key)
            days_remaining = max(0, remaining_ttl // (24 * 60 * 60))
            
            logger.warning("onboarding_limit_exceeded", extra={"tenant_id": tenant_id, "count": interview_count})
            
            return {
                "error": "Onboarding Limit Reached",
                "detail": f"Has utilizado tus 5 entrevistas gratuitas. Para continuar creando agentes, configura tu propia API Key de OpenAI en el Credential Vault. El límite se reiniciará en {days_remaining} días.",
                "action_required": "configure_api_key",
                "limit_reset_days": days_remaining,
                "ai_message": "🔒 **Límite Alcanzado**: Has completado tus 5 entrevistas de prueba. Para continuar, ve a **Configuración → Credenciales** y agrega tu OpenAI API Key."
            }

        # 2. Append User Message
        ONBOARDING_SESSIONS[session_id].append({"role": "user", "content": user_message})

        # 3. Get Credentials — platform key (company pays for onboarding)
        api_key = await _get_platform_key(tenant_id)
        client = openai.AsyncOpenAI(api_key=api_key)

        # 4. Generate AI Response
        response = await client.chat.completions.create(
            model="gpt-4o",
            messages=ONBOARDING_SESSIONS[session_id],
            temperature=0.7
        )

        ai_text = response.choices[0].message.content
        ONBOARDING_SESSIONS[session_id].append({"role": "assistant", "content": ai_text})

        # 5. Check for <CONFIG_READY> (Regex Robustness)
        import re
        config_ready = False
        extracted_data = None
        
        # Pattern to find anything between <CONFIG_READY> tags, ignoring case and multi-line
        pattern = re.compile(r"<CONFIG_READY>(.*?)</CONFIG_READY>", re.DOTALL | re.IGNORECASE)
        match = pattern.search(ai_text)

        if match:
            config_ready = True
            try:
                json_str = match.group(1).strip()
                
                # Robustness: Remove markdown code blocks if present (```json or ```)
                json_str = re.sub(r"```(?:json)?\n?|\n?```", "", json_str).strip()
                
                extracted_data = json.loads(json_str)
                
                # Clean the response for the UI (remove the whole block)
                ai_text = pattern.sub("", ai_text).strip()
            except Exception as e:
                logger.error(f"JSON Parsing Error in Onboarding: {e}")
                config_ready = False

        return {
            "ai_message": ai_text,
            "config_ready": config_ready,
            "extracted_data": extracted_data
        }

    except Exception as e:
        logger.error(f"Onboarding Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/generate")
async def onboarding_generate(
    tenant_id: int = Body(..., embed=True),
    final_config: dict = Body(..., embed=True),
    db: AsyncSession = Depends(get_db)
):
    """
    Finalizes the onboarding: Creates the agent in the DB.
    """
    # Use the extracted data to create a 'Sales' agent
    from sqlalchemy import text
    # 1. Prepare JSON Config
    wizard_config = {
        "store_name": final_config.get("agent_name", "Nuevo Agente"),
        "business_description": final_config.get("store_description", ""),
        "agent_tone": final_config.get("agent_tone", ""),
        "business_rules": final_config.get("business_rules", ""),
        "synonym_dictionary": final_config.get("synonym_dictionary", ""),
        "website_url": final_config.get("store_website", ""),
        "store_address": final_config.get("store_address", ""),
        "shipping_partners": final_config.get("shipping_partners", ""),
        "catalog_knowledge": final_config.get("catalog_knowledge", ""),
        "template_type": "sales",
    }

    # 2. Insert into DB
    # We follow the same pattern as get_or_create_sales_agent but forcing a new one
    q_insert = text("""
        INSERT INTO agents (name, role, tenant_id, config, model_provider, model_version, is_active, enabled_tools, system_prompt_template, template_type)
        VALUES (:name, :role, :tenant_id, :config :: jsonb, :provider, :version, :is_active, :tools :: jsonb, :prompt, :template_type)
        RETURNING id
    """)

    try:
        result = await db.execute(q_insert, {
            "name": final_config.get("agent_name", "Agente IA"),
            "role": "sales", # Default role for Hyper-Onboarding
            "tenant_id": tenant_id,
            "config": json.dumps(wizard_config),
            "provider": "openai",
            "version": "gpt-4o",
            "is_active": True,
            "tools": json.dumps(["search_specific_products", "search_by_category", "browse_general_storefront", "orders", "derivhumano"]), # Standard Suite
            "prompt": "Eres un asistente virtual de ventas.", # Pivot: Placeholder prompt to satisfy NotNull constraint. Wizard will overwrite.
            "template_type": "sales"
        })
        await db.commit()
        new_id = result.scalar()
        
        return {"agent_id": new_id, "status": "created"}
        
    except Exception as e:
        logger.error(f"Failed to create agent via Onboarding: {e}")
        raise HTTPException(status_code=500, detail=str(e))
@router.post("/draft")
async def onboarding_draft(
    tenant_id: int = Body(..., embed=True),
    final_config: dict = Body(..., embed=True),
    db: AsyncSession = Depends(get_db)
):
    """
    Saves the Architect's output as a DRAFT agent (is_active=False).
    Returns draft_id for the Wizard to hydrate.
    """
    from sqlalchemy import text
    import json
    
    # 1. Prepare Wizard Config
    wizard_config = {
        "store_name": final_config.get("agent_name", "Nuevo Agente (Borrador)"),
        "business_description": final_config.get("store_description", ""),
        "agent_tone": final_config.get("agent_tone", ""),
        "business_rules": final_config.get("business_rules", ""),
        "synonym_dictionary": final_config.get("synonym_dictionary", ""),
        "website_url": final_config.get("store_website", ""),
        "store_address": final_config.get("store_address", ""),
        "shipping_partners": final_config.get("shipping_partners", ""),
        "catalog_knowledge": final_config.get("catalog_knowledge", ""),
        "template_type": "sales",
    }

    # 2. Insert into DB as INACTIVE
    q_insert = text("""
        INSERT INTO agents (name, role, tenant_id, config, model_provider, model_version, is_active, enabled_tools, system_prompt_template, template_type)
        VALUES (:name, :role, :tenant_id, :config :: jsonb, :provider, :version, :is_active, :tools :: jsonb, :prompt, :template_type)
        RETURNING id
    """)

    try:
        result = await db.execute(q_insert, {
            "name": f"[DRAFT] {final_config.get('agent_name', 'Agente')}", 
            "role": "sales", 
            "tenant_id": tenant_id,
            "config": json.dumps(wizard_config),
            "provider": "openai",
            "version": "gpt-4o",
            "is_active": False, # <--- DRAFT MODE
            "tools": json.dumps(["search_specific_products", "search_by_category", "browse_general_storefront", "orders", "derivhumano"]),
            "prompt": "[DRAFT] Pendiente de generacion.", # Pivot: Placeholder for draft
            "template_type": "sales"
        })
        await db.commit()
        draft_id = result.scalar()
        
        return {"draft_id": draft_id, "status": "draft_saved"}
        
    except Exception as e:
        logger.error(f"Failed to save draft: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# --- Wizard Interview Step (Section-Scoped Chat) ---

WIZARD_STEP_SESSIONS = {}

WIZARD_STEP_PROMPTS = {
    3: """Sos la Arquitecta de Agentes de IA. Tu nombre es Nova. Sos argentina, calida, profesional y extremadamente inteligente. Hablas con voseo natural.

FORMATO: Tus respuestas se reproducen como audio. REGLAS INQUEBRANTABLES:
- Solo texto plano conversacional. JAMAS uses markdown, asteriscos, guiones, listas, ni formatos de texto.
- JAMAS uses emojis.
- Maximo 3-4 oraciones por respuesta. Sos concisa pero profunda.
- Pregunta UNA sola cosa por vez. Espera respuesta.

CONTEXTO: Si recibis datos de redes sociales (CONTEXTO EXTRAIDO), usalos inteligentemente. No los recites, demostrale al usuario que ya investigaste su negocio. Ejemplo: en vez de "Vi que tu bio dice X", deci "Noto que tu marca tiene un enfoque en X, me encanta. Contame mas sobre eso."

EJEMPLO DE CALIDAD OBJETIVO (estudia este nivel de profundidad — Pointe Coach):
El system prompt final debe tener esta densidad:
- TONO: "Habla como una companera experta. Usa vos. Se calida. Prohibido frases de telemarketing. Usa frases puente como Mira, Te cuento, Fijate, Dale."
- REGLAS: "VERACIDAD ABSOLUTA: PROHIBIDO inventar precios, stock o variantes. DERIVACION: Usa derivhumano si el cliente esta enojado."
- DICCIONARIO: "ZAPATILLAS DE PUNTA: puntas, pointe, pointe shoes. MEDIA PUNTA: media punta, zapatillas de tela, slippers."

TU META: Generar un prompt con ESA densidad y especificidad. No aceptes respuestas genericas.

ESTRATEGIA DE ENTREVISTA (5 fases, una por vez):

FASE 1 - RECONOCIMIENTO (usa datos de redes si los tenes):
Si tenes contexto de redes, arranca asi: "Hola! Soy Nova, tu arquitecta de IA. Ya estuve investigando tu negocio y tengo algunas ideas. Veo que se dedican a [DATO DE REDES]. Antes de arrancar, necesito que me cuentes con tus palabras: cual es la historia de tu negocio? Como empezo, que los mueve, y sobre todo, quien es ese cliente que entra y dice 'esto es para mi'?"

Si NO tenes contexto: "Hola! Soy Nova, tu arquitecta de IA. Vamos a crear algo increible juntos. Necesito que me cuentes todo sobre tu negocio como si yo fuera una amiga que recien conoce tu marca. Como se llama? Que venden? Y lo mas importante: quien es tu cliente ideal, esa persona que representa tu comprador perfecto?"

PROFUNDIZAR SIEMPRE: Si da una respuesta de menos de 30 palabras, pedi mas:
"Necesito que te explayes un poco mas. Pensalo asi: si tuvieras que presentar tu negocio a un inversor en 3 minutos, que le dirias? Que edad tiene tu cliente tipico? Que busca: precio, calidad, exclusividad, comodidad? Contame un caso real de alguien que te compro y por que eligio tu tienda."

Cuando tengas: nombre + rubro + cliente ideal + diferencial + historia, emiti: <CONFIRM:identidad>
Decile: "Perfecto, ya tengo claro el ADN de tu negocio. Ahora vamos a definir exactamente como habla tu agente."

FASE 2 - TONO Y VOZ:
Usa escenario concreto: "Imaginemos que una clienta nueva te escribe por WhatsApp: 'Hola, tienen vestidos para una fiesta?' Como le responderias vos personalmente? Decime literal que le escribirias."

Despues pregunta: "Y cuando tratamos a los clientes, es de vos, de tu, o de usted? Somos mas formales tipo 'Le recomiendo este modelo' o mas de barrio tipo 'Mira, este te va a quedar tremendo'?"

Cuando tengas pronombres + formalidad + ejemplo real de respuesta, emiti: <CONFIRM:tono>
Decile: "Genial, ya capture la voz de tu marca."

FASE 3 - ESTILO Y MULETILLAS:
"Ahora el estilo fino. Usas emojis con tus clientes? Cuales te salen naturales? Y hay frases que uses siempre, esas muletillas que son tu sello? Por ejemplo, hay gente que siempre dice 'Genial!', otros dicen 'Barbaro', otros 'Dale dale'..."

"Y la otra cara: que frases o palabras JAMAS usarias? Cosas que te suenan falsas, corporativas, o que no van con tu identidad."

Cuando tengas, emiti: <CONFIRM:estilo>

FASE 4 - RESTRICCIONES CRITICAS:
"Ultima pregunta de identidad, y es clave. Que cosas tu agente NO debe decir o hacer NUNCA? Pensa en lo que te daria panico. Por ejemplo: inventar que hay stock, prometer descuentos, dar tiempos de entrega que no podes cumplir, recomendar productos de la competencia..."

Cuando tengas, emiti: <CONFIRM:restricciones>

FASE 5 - GENERACION:
Genera el draft con la MISMA DENSIDAD que Pointe Coach. Cada seccion debe tener al menos 3-4 reglas especificas. No simplifiques. Emiti:
<SECTION_COMPLETE>{"section": "tone", "draft": "## TONO Y PERSONALIDAD\\n\\n* Estilo: [ESPECIFICO AL NEGOCIO]\\n* Pronombres: [vos/tu/usted]\\n* Puntuacion: [reglas especificas]\\n* Prohibido: [lista concreta]\\n* Naturalidad: [frases puente del negocio]\\n* Emojis: [cuales si, cuales no]"}</SECTION_COMPLETE>""",

    4: """Sos Nova, la Arquitecta de Reglas. Argentina, calida, profesional, voseo natural.

FORMATO: Texto plano, sin markdown ni emojis. Maximo 3-4 oraciones. UNA pregunta por vez.

OBJETIVO: Extraer reglas operativas con la precision de un contrato. Cada regla debe ser un IMPERATIVO claro. No aceptes "somos flexibles" — necesitas numeros, plazos, excepciones.

EJEMPLO DE DENSIDAD OBJETIVO (Pointe Coach):
"1. VERACIDAD ABSOLUTA: PROHIBIDO inventar precios, stock o variantes.
2. DERIVACION: Usa derivhumano si el cliente esta enojado o pide hablar con persona.
3. FITTING: Ofrecelo exclusivamente para zapatillas de punta. Si acepta, derivar a humano.
4. ENVIOS: Trabajamos con Andreani. El costo se calcula en el checkout."

Cada regla es un imperativo concreto, no una sugerencia.

ESTRATEGIA (4 fases):

FASE 1 - ENVIOS:
"Ahora las reglas de tu negocio. Empecemos con envios. Hacen envios? A todo el pais o solo ciertas zonas? Cuanto cobran, o hay envio gratis desde cierto monto? Con que empresa trabajan?"

Si dice "envio gratis arriba de cierto monto": "Perfecto. Cual es ese monto exacto? Y debajo de ese monto, cuanto sale el envio? Cuantos dias tarda?"

Cuando tengas datos concretos (numeros, plazos, zonas, empresa), emiti: <CONFIRM:envios>

FASE 2 - CAMBIOS:
Usa escenario: "Un cliente te escribe: 'Me queda grande, lo quiero cambiar.' Que le decis? Tiene plazo para cambiar? Tiene que tener el ticket? Y que pasa con productos intimos, en oferta, o personalizados? Hay algo que no tenga cambio?"

Si dice algo vago como "si, aceptamos cambios": "Necesito los detalles: en cuantos dias? El producto tiene que estar sin uso? Quien paga el envio del cambio? Y devolucion con reembolso es posible o solo cambio?"

Cuando tengas reglas concretas con plazos y excepciones, emiti: <CONFIRM:cambios>

FASE 3 - OPERATIVA:
"Horario de atencion: de que hora a que hora atienden? Que dias? Y fuera de horario, el agente dice 'te respondemos manana' o responde igual?"

"Formas de pago: MercadoPago, tarjeta, transferencia, efectivo? Hacen cuotas? Descuento por transferencia?"

"Y el proceso de compra: el cliente elige por chat y le mandas un link de pago? Lo derivas a la web? Le tomas el pedido directo? Explicame como cierra una venta tipica."

Cuando tengas, emiti: <CONFIRM:operativa>

FASE 4 - PROHIBICIONES + GENERACION:
"Que NO debe hacer el agente NUNCA? Pensalo como un empleado nuevo: que le dirias el primer dia que no haga jamas? Por ejemplo, nunca inventar stock, nunca prometer envio gratis si no corresponde, nunca dar el precio de un competidor..."

Cuando tengas, emiti: <CONFIRM:prohibiciones>

Genera con DENSIDAD POINTE COACH:
<SECTION_COMPLETE>{"section": "rules", "draft": "## REGLAS DE NEGOCIO\\n\\n### REGLAS UNIVERSALES DE SEGURIDAD\\n1. VERACIDAD ABSOLUTA: PROHIBIDO inventar precios, stock o variantes.\\n2. ALCANCE: Solo responder sobre la tienda y proceso de compra.\\n3. DERIVACION: Usar derivhumano si el cliente esta enojado o pide hablar con persona.\\n\\n### REGLAS ESPECIFICAS\\n4. ENVIOS: [datos concretos]\\n5. CAMBIOS: [plazos y excepciones]\\n6. HORARIOS: [dias y horas]\\n7. PAGOS: [metodos aceptados]\\n8. PROCESO DE COMPRA: [como se cierra]\\n9. PROHIBICIONES: [lista concreta]"}</SECTION_COMPLETE>""",

    5: """Sos Nova, la Arquitecta de Diccionario. Argentina, calida, profesional, voseo natural.

FORMATO: Texto plano, sin markdown ni emojis. Maximo 4-5 oraciones por respuesta. UNA fase por vez.

OBJETIVO: Generar un diccionario MASIVO de sinonimos. La clave es que VOS GENERAS LA BASE COMPLETA usando toda la info que tenes de la conversacion anterior (el rubro, los productos, el tipo de cliente, datos de redes sociales). El usuario solo CONFIRMA, CORRIGE y AGREGA lo que falte. NO le pidas que invente sinonimos desde cero. Vos haces el trabajo pesado.

EJEMPLO DE DENSIDAD OBJETIVO (Pointe Coach, 8-12 sinonimos por item):
"ZAPATILLAS DE PUNTA: puntas, zapatillas de punta, pointe, pointe shoes, calzado de punta, zapatos de punta, zapatos de ballet, zapatillas para puntas.
MEDIA PUNTA: media punta, medias puntas, zapatillas de ensayo, zapatillas de tela, slippers de ballet, slippers, zapatillas blandas, zapatillas de practica.
LEOTARDOS: malla, mallas, leotardo, leotard, maillot, body, malla de ballet, body de danza, enterito, enteriza, malla entera, body entero."

ESTRATEGIA (3 fases):

FASE 1 - GENERAR BASE PROACTIVA:
Arranca diciendo: "Ultima seccion y es mi favorita. Ya se bastante sobre tu negocio asi que hice el trabajo previo. Arme un diccionario base con todos los sinonimos que se me ocurren para tus productos. Te lo comparto y vos me decis si falta algo o si algun sinonimo esta mal."

Entonces GENERA VOS MISMA una base amplia de sinonimos usando:
1. Los productos y categorias que el usuario menciono en las fases anteriores
2. Los datos de redes sociales si los tenes (nombres de productos en posts, captions, bio)
3. Tu conocimiento del sector (sinonimos tipicos del rubro en Argentina, Mexico, Colombia, Chile, etc)
4. Variantes coloquiales, informales, y tecnicas de cada producto
5. Como lo buscarian en Google vs como lo pedirian por WhatsApp

Ejemplo para una tienda de ropa: "Arme esto basandome en lo que me contaste. REMERAS incluye remera, camiseta, t-shirt, playera, polera, franela, musculosa si es sin mangas. PANTALONES incluye pantalon, jean, vaquero, jogger, cargo, chupines, calzas si son ajustados. BUZOS incluye buzo, hoodie, canguro, sudadera, poleron, campera si es con cierre. Que te parece? Falta algo importante?"

Cuando el usuario confirme o amplie, emiti: <CONFIRM:categorias>
Decile: "Genial, los productos estan cubiertos. Ahora la jerga de WhatsApp."

FASE 2 - JERGA, ABREVIACIONES Y ERRORES (tambien generar base):
"Tambien prepare la jerga basica que es comun en todos los negocios online. Te la leo: MP o Merca por MercadoPago. Transf por transferencia. Dispo por disponible. Para consultar precio tus clientes pueden decir cuanto sale, a cuanto esta, que valor tiene, precio, cuanto cuesta, sale. Y errores tipicos como cuanto bale con b, aver junto, tenes sin tilde, ai en vez de hay. Hay alguna jerga especifica de tu sector que yo no tenga?"

Cuando confirme, emiti: <CONFIRM:jerga>

FASE 3 - GENERACION FINAL:
Genera el diccionario MAS COMPLETO POSIBLE. Incluye TODO lo que el usuario confirmo mas todo lo que vos generaste. Minimo 8 sinonimos por categoria de producto principal. Incluye variantes de Argentina, Mexico, Colombia, Chile, Espana.

<SECTION_COMPLETE>{"section": "dictionary", "draft": "## DICCIONARIO DE SINONIMOS Y JERGA\\n\\n### Productos y Categorias\\n* [PRODUCTO 1]: sinonimo1, sinonimo2, sinonimo3, sinonimo4, sinonimo5, sinonimo6, sinonimo7, sinonimo8.\\n* [PRODUCTO 2]: sinonimo1, sinonimo2, sinonimo3, sinonimo4, sinonimo5, sinonimo6.\\n* [PRODUCTO 3]: ...\\n\\n### Consultas frecuentes\\n* PRECIO: cuanto sale, que valor tiene, a cuanto esta, precio, cuanto cuesta, sale?, valor, que precio tiene, cuanto vale, cuanto es.\\n* DISPONIBILIDAD: tenes, tienen, hay, esta disponible, hay stock, queda, les queda, lo tienen, esta.\\n* ENVIO: hacen envios, envian, mandan, despachan, llega a mi zona, envio a domicilio, hacen delivery, mandan a domicilio.\\n* TALLE: que talles tienen, medidas, talle, size, que numeros hay, tabla de talles.\\n\\n### Abreviaciones WhatsApp\\n* MERCADOPAGO: merca, mp, mercado pago, mercpago, mercadopago.\\n* TRANSFERENCIA: transf, transfer, transferencia bancaria, deposito, cbu, alias.\\n* DISPONIBLE: dispo, disponble, disp.\\n* POR FAVOR: xfa, porfavor, porfa, x favor.\\n\\n### Errores ortograficos comunes\\n* DISPONIBLE: disponble, dispnible, dispo.\\n* A VER: aver, haver, a ber.\\n* CUANTO VALE: cuanto bale, cuanto bal, quanto vale.\\n* HAY: ai, hay, ahi (confundido).\\n* ENVIO: envio, embio, envian, embian."}</SECTION_COMPLETE>

Decile: "Diccionario completo. Tu agente ahora entiende absolutamente todo lo que un cliente le pueda escribir, incluyendo jerga, abreviaciones y errores de ortografia. Esto es lo que marca la diferencia entre un bot generico y un agente que realmente entiende a tus clientes."

REGLA DE ORO: El usuario NO debe pensar mucho. Vos haces el 90 por ciento del trabajo. El solo confirma, corrige y agrega lo que falte. Si dice "esta todo bien", avanza. Si dice "falta X", agregalo y volve a mostrar."""
}


@router.post("/interview-step")
async def onboarding_interview_step(
    session_id: str = Body(..., embed=True),
    user_message: str = Body(..., embed=True),
    step: int = Body(..., embed=True),
    tenant_id: int = Body(0, embed=True),
    reset: bool = Body(False, embed=True),
    chat_history: list = Body([], embed=True),
):
    """
    Section-scoped interview for wizard steps 3, 4, 5.
    Each step uses a different prompt focused on that section.
    Accepts chat_history to re-seed context when user returns after closing.
    """
    if step not in WIZARD_STEP_PROMPTS:
        raise HTTPException(status_code=400, detail=f"Invalid step {step}. Must be 3, 4, or 5.")

    try:
        # Initialize or reset session
        step_session_key = f"{session_id}_step{step}"
        if reset or step_session_key not in WIZARD_STEP_SESSIONS:
            WIZARD_STEP_SESSIONS[step_session_key] = [
                {"role": "system", "content": WIZARD_STEP_PROMPTS[step]}
            ]

            # Re-seed with chat history if user is returning
            if chat_history and len(chat_history) > 0:
                for msg in chat_history:
                    role = msg.get("role", "user")
                    content = msg.get("content", "")
                    if role in ("user", "assistant") and content:
                        WIZARD_STEP_SESSIONS[step_session_key].append({"role": role, "content": content})
                # Tell the AI to continue where it left off
                user_message = "Retome la conversacion donde la dejamos. Que falta por configurar de esta seccion?"
            elif reset:
                user_message = "Hola, estoy listo para configurar esta seccion."

        # Append user message
        WIZARD_STEP_SESSIONS[step_session_key].append({"role": "user", "content": user_message})

        # Use platform API key (company pays for onboarding)
        api_key = await _get_platform_key(tenant_id)
        client = openai.AsyncOpenAI(api_key=api_key)

        response = await client.chat.completions.create(
            model="gpt-4o",
            messages=WIZARD_STEP_SESSIONS[step_session_key],
            temperature=0.7
        )

        ai_text = response.choices[0].message.content
        WIZARD_STEP_SESSIONS[step_session_key].append({"role": "assistant", "content": ai_text})

        # Check for CONFIRM tags (sub-section confirmations)
        confirm_section = None
        confirm_pattern = re.compile(r"<CONFIRM:(\w+)>", re.IGNORECASE)
        confirm_match = confirm_pattern.search(ai_text)
        if confirm_match:
            confirm_section = confirm_match.group(1)
            ai_text = confirm_pattern.sub("", ai_text).strip()

        # Check for SECTION_COMPLETE (full section done)
        section_complete = False
        extracted_draft = None

        pattern = re.compile(r"<SECTION_COMPLETE>(.*?)</SECTION_COMPLETE>", re.DOTALL | re.IGNORECASE)
        match = pattern.search(ai_text)

        if match:
            section_complete = True
            try:
                json_str = re.sub(r"```(?:json)?\n?|\n?```", "", match.group(1).strip()).strip()
                data = json.loads(json_str)
                extracted_draft = data.get("draft", "")
                ai_text = pattern.sub("", ai_text).strip()
            except Exception as e:
                logger.error(f"Section complete parse error: {e}")
                section_complete = False

        return {
            "ai_message": ai_text,
            "section_complete": section_complete,
            "extracted_draft": extracted_draft,
            "confirm_section": confirm_section,
            "step": step
        }

    except Exception as e:
        logger.error(f"Interview step error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# --- TTS Endpoint (Voice Architect) ---

@router.post("/tts")
async def onboarding_tts(text: str = Body(..., embed=True)):
    """Convert text to speech using OpenAI TTS. Returns MP3 audio bytes.
    Uses platform API key (company investment in onboarding UX).
    Voice: nova (femenina, cálida, ideal para LATAM).
    """
    try:
        api_key = await _get_platform_key()
        client = openai.AsyncOpenAI(api_key=api_key)

        response = await client.audio.speech.create(
            model="tts-1",
            voice="nova",
            input=text,
            response_format="mp3"
        )

        # Read full audio content
        audio_bytes = response.read()

        from fastapi.responses import Response
        return Response(content=audio_bytes, media_type="audio/mpeg")

    except Exception as e:
        logger.error(f"TTS error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# --- Realtime Voice Session (OpenAI Realtime API — like Voice Widget) ---

@router.post("/realtime-session")
async def create_realtime_session(
    step: int = Body(3, embed=True),
    tenant_id: int = Body(0, embed=True),
    meta_context: str = Body("", embed=True),
):
    """Create an OpenAI Realtime session for the voice architect.
    Returns session_id and ws_url for WebSocket connection."""
    import uuid
    from db import redis_client

    api_key = await _get_platform_key(tenant_id)

    # Build Nova's system prompt with meta context
    base_prompt = WIZARD_STEP_PROMPTS.get(step, WIZARD_STEP_PROMPTS[3])

    # Strip voice format instructions (Realtime handles voice natively)
    # Add meta context if available
    system_prompt = base_prompt
    if meta_context:
        system_prompt = f"""CONTEXTO DE REDES SOCIALES DEL NEGOCIO:
{meta_context}

Usa esta informacion para personalizar tus preguntas. No la recites, demostrale al usuario que ya investigaste su negocio.

{base_prompt}"""

    session_id = uuid.uuid4().hex
    session_data = {
        "type": "onboarding_realtime",
        "step": step,
        "tenant_id": tenant_id,
        "api_key": api_key,
        "system_prompt": system_prompt,
        "voice": "nova",
        "max_duration": 600,  # 10 min max for onboarding conversation
    }

    await redis_client.setex(
        f"onboarding_realtime:{session_id}",
        660,  # TTL = max_duration + margin
        json.dumps(session_data)
    )

    logger.info("onboarding_realtime_session_created", step=step, session_id=session_id)
    return {"session_id": session_id, "step": step}


# --- Meta Data Extraction (for Architect context) ---

@router.post("/extract-meta-data")
async def extract_meta_data(tenant_id: int = Body(0, embed=True)):
    """
    Extract business data from connected Meta assets (FB pages + Instagram).
    Uses stored tokens to fetch profile info, recent posts, bio, category.
    Returns structured context for the architect to use.
    """
    from db import db
    from utils import decrypt_password
    import httpx

    # If no tenant_id provided, try to find the most recent one
    if not tenant_id:
        row = await db.pool.fetchrow(
            "SELECT tenant_id FROM onboarding_progress WHERE tenant_id IS NOT NULL ORDER BY updated_at DESC LIMIT 1"
        )
        if row:
            tenant_id = row["tenant_id"]
    if not tenant_id:
        return {"context": "", "assets": [], "debug": "no_tenant_id"}

    try:
        # 1. Get business assets from DB
        logger.info(f"extract_meta_data: tenant_id={tenant_id}")
        assets = await db.pool.fetch(
            "SELECT asset_type, content FROM business_assets WHERE tenant_id = $1 AND is_active = true",
            tenant_id
        )
        logger.info(f"extract_meta_data: found {len(assets)} assets")

        extracted = []
        api_version = "v22.0"

        for asset in assets:
            asset_type = asset["asset_type"]
            content = asset["content"] if isinstance(asset["content"], dict) else json.loads(asset["content"] or "{}")
            asset_id = content.get("id", "")
            asset_name = content.get("name", "") or content.get("username", "")

            if not asset_id:
                continue

            # Get token for this asset
            token_row = await db.pool.fetchrow(
                "SELECT value FROM credentials WHERE tenant_id = $1 AND name = $2",
                tenant_id, f"META_PAGE_TOKEN_{asset_id}"
            )
            # Try linked page token for Instagram
            if not token_row and asset_type == "instagram":
                linked_page_id = content.get("linked_page_id")
                if linked_page_id:
                    token_row = await db.pool.fetchrow(
                        "SELECT value FROM credentials WHERE tenant_id = $1 AND name = $2",
                        tenant_id, f"META_PAGE_TOKEN_{linked_page_id}"
                    )

            if not token_row:
                extracted.append({"type": asset_type, "name": asset_name, "data": "Token no disponible"})
                continue

            token = decrypt_password(token_row["value"])

            async with httpx.AsyncClient(timeout=10.0) as client:
                if asset_type == "page":
                    # Facebook Page: name, category, about, description, fan_count
                    resp = await client.get(
                        f"https://graph.facebook.com/{api_version}/{asset_id}",
                        params={"fields": "name,category,about,description,fan_count,website,phone", "access_token": token}
                    )
                    if resp.status_code == 200:
                        page_data = resp.json()
                        extracted.append({
                            "type": "facebook_page",
                            "name": page_data.get("name", ""),
                            "category": page_data.get("category", ""),
                            "about": page_data.get("about", ""),
                            "description": page_data.get("description", ""),
                            "fans": page_data.get("fan_count", 0),
                            "website": page_data.get("website", ""),
                            "phone": page_data.get("phone", ""),
                        })

                    # Recent posts
                    posts_resp = await client.get(
                        f"https://graph.facebook.com/{api_version}/{asset_id}/posts",
                        params={"fields": "message,created_time", "limit": "5", "access_token": token}
                    )
                    if posts_resp.status_code == 200:
                        posts = posts_resp.json().get("data", [])
                        extracted.append({
                            "type": "facebook_posts",
                            "posts": [p.get("message", "")[:200] for p in posts if p.get("message")]
                        })

                elif asset_type == "instagram":
                    # Instagram: name, username, biography, followers, media_count
                    resp = await client.get(
                        f"https://graph.facebook.com/{api_version}/{asset_id}",
                        params={"fields": "name,username,biography,followers_count,media_count,website", "access_token": token}
                    )
                    if resp.status_code == 200:
                        ig_data = resp.json()
                        extracted.append({
                            "type": "instagram_profile",
                            "name": ig_data.get("name", ""),
                            "username": ig_data.get("username", ""),
                            "bio": ig_data.get("biography", ""),
                            "followers": ig_data.get("followers_count", 0),
                            "media_count": ig_data.get("media_count", 0),
                            "website": ig_data.get("website", ""),
                        })

                    # Recent media captions
                    media_resp = await client.get(
                        f"https://graph.facebook.com/{api_version}/{asset_id}/media",
                        params={"fields": "caption,timestamp,media_type", "limit": "5", "access_token": token}
                    )
                    if media_resp.status_code == 200:
                        media = media_resp.json().get("data", [])
                        extracted.append({
                            "type": "instagram_posts",
                            "posts": [m.get("caption", "")[:200] for m in media if m.get("caption")]
                        })

        # Build context string for the architect
        context_parts = []
        for item in extracted:
            if item["type"] == "facebook_page":
                context_parts.append(f"PAGINA DE FACEBOOK: {item['name']}. Categoria: {item.get('category','')}. Descripcion: {item.get('about','')}. Fans: {item.get('fans',0)}. Web: {item.get('website','')}")
            elif item["type"] == "facebook_posts":
                if item["posts"]:
                    context_parts.append(f"ULTIMOS POSTS DE FACEBOOK: " + " | ".join(item["posts"][:3]))
            elif item["type"] == "instagram_profile":
                context_parts.append(f"PERFIL DE INSTAGRAM: @{item.get('username','')}. Bio: {item.get('bio','')}. Seguidores: {item.get('followers',0)}. Publicaciones: {item.get('media_count',0)}. Web: {item.get('website','')}")
            elif item["type"] == "instagram_posts":
                if item["posts"]:
                    context_parts.append(f"ULTIMOS POSTS DE INSTAGRAM: " + " | ".join(item["posts"][:3]))

        context = "\n".join(context_parts)
        return {"context": context, "assets": extracted}

    except Exception as e:
        logger.error(f"Meta data extraction error: {e}")
        return {"context": "", "assets": [], "error": str(e)}
