from fastapi import APIRouter, Depends, HTTPException, Body
from sqlalchemy.ext.asyncio import AsyncSession
from db import get_db
from app.core.prompts import ONBOARDING_ARCHITECT_PROMPT
from app.core.credentials import get_tenant_credential_by_type
import openai
import json
import logging

router = APIRouter()
logger = logging.getLogger(__name__)

# Memory Store (In-Memory for now, ideally Redis)
# Format: { "session_id": [ {"role": "system", ...}, {"role": "user", ...} ] }
ONBOARDING_SESSIONS = {}

@router.post("/interview")
async def onboarding_interview(
    session_id: str = Body(..., embed=True),
    user_message: str = Body(..., embed=True),
    tenant_id: int = Body(..., embed=True),
    reset: bool = Body(False, embed=True),
    db: AsyncSession = Depends(get_db)
):
    """
    Handles the turn-by-turn interview with the AI Architect.
    """
    try:
        # 1. Initialize Session
        if reset or session_id not in ONBOARDING_SESSIONS:
            ONBOARDING_SESSIONS[session_id] = [
                {"role": "system", "content": ONBOARDING_ARCHITECT_PROMPT}
            ]
            # Initial greeting is generated by AI, so we trigger empty run if reset
            if reset:
                 user_message = "Hola, quiero crear mi agente."

        # Nexus v7.6.1 Security Audit: Onboarding Usage Limits (P3 Remediation)
        # Enforce 5 free interviews per tenant, then require API key configuration
        from db import redis_client
        
        onboarding_key = f"onboarding:interviews:{tenant_id}"
        interview_count = await redis_client.incr(onboarding_key)
        
        # Set 30-day TTL on first use
        if interview_count == 1:
            await redis_client.expire(onboarding_key, 30 * 24 * 60 * 60)  # 30 days in seconds
        
        # Check limit (5 interviews max before requiring own API key)
        if interview_count > 5:
            remaining_ttl = await redis_client.ttl(onboarding_key)
            days_remaining = max(0, remaining_ttl // (24 * 60 * 60))
            
            logger.warning("onboarding_limit_exceeded", extra={"tenant_id": tenant_id, "count": interview_count})
            
            return {
                "error": "Onboarding Limit Reached",
                "detail": f"Has utilizado tus 5 entrevistas gratuitas. Para continuar creando agentes, configura tu propia API Key de OpenAI en el Credential Vault. El límite se reiniciará en {days_remaining} días.",
                "action_required": "configure_api_key",
                "limit_reset_days": days_remaining,
                "ai_message": "🔒 **Límite Alcanzado**: Has completado tus 5 entrevistas de prueba. Para continuar, ve a **Configuración → Credenciales** y agrega tu OpenAI API Key."
            }

        # 2. Append User Message
        ONBOARDING_SESSIONS[session_id].append({"role": "user", "content": user_message})

        # 3. Get Credentials (Sovereign)
        # We need a system key for the Architect. 
        # Ideally this comes from the tenant, but for onboarding we might use a platform key if tenant has none yet.
        # For now, let's assume tenant has a key or we use env (fallback).
        api_key = await get_tenant_credential_by_type(tenant_id, "OPENAI_API_KEY")
        if not api_key:
             # Fallback logic or error - for now hard error to enforce Sovereign protocol
             # But for onboarding, maybe we use a platform key? Let's check env as fallback for Architect only.
             import os
             api_key = os.getenv("OPENAI_API_KEY") 
        
        client = openai.AsyncOpenAI(api_key=api_key)

        # 4. Generate AI Response
        response = await client.chat.completions.create(
            model="gpt-4o",
            messages=ONBOARDING_SESSIONS[session_id],
            temperature=0.7
        )

        ai_text = response.choices[0].message.content
        ONBOARDING_SESSIONS[session_id].append({"role": "assistant", "content": ai_text})

        # 5. Check for <CONFIG_READY> (Regex Robustness)
        import re
        config_ready = False
        extracted_data = None
        
        # Pattern to find anything between <CONFIG_READY> tags, ignoring case and multi-line
        pattern = re.compile(r"<CONFIG_READY>(.*?)</CONFIG_READY>", re.DOTALL | re.IGNORECASE)
        match = pattern.search(ai_text)

        if match:
            config_ready = True
            try:
                json_str = match.group(1).strip()
                
                # Robustness: Remove markdown code blocks if present (```json or ```)
                json_str = re.sub(r"```(?:json)?\n?|\n?```", "", json_str).strip()
                
                extracted_data = json.loads(json_str)
                
                # Clean the response for the UI (remove the whole block)
                ai_text = pattern.sub("", ai_text).strip()
            except Exception as e:
                logger.error(f"JSON Parsing Error in Onboarding: {e}")
                config_ready = False

        return {
            "ai_message": ai_text,
            "config_ready": config_ready,
            "extracted_data": extracted_data
        }

    except Exception as e:
        logger.error(f"Onboarding Error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/generate")
async def onboarding_generate(
    tenant_id: int = Body(..., embed=True),
    final_config: dict = Body(..., embed=True),
    db: AsyncSession = Depends(get_db)
):
    """
    Finalizes the onboarding: Creates the agent in the DB.
    """
    # Use the extracted data to create a 'Sales' agent
    from sqlalchemy import text
    # 1. Prepare JSON Config
    wizard_config = {
        "store_name": final_config.get("agent_name", "Nuevo Agente"),
        "business_description": final_config.get("store_description", ""),
        "agent_tone": final_config.get("agent_tone", ""),
        "business_rules": final_config.get("business_rules", ""),
        "synonym_dictionary": final_config.get("synonym_dictionary", ""),
        "website_url": final_config.get("store_website", ""),
        "store_address": final_config.get("store_address", ""),
        "shipping_partners": final_config.get("shipping_partners", ""),
        "catalog_knowledge": final_config.get("catalog_knowledge", ""),
        "template_type": "sales",
    }

    # 2. Insert into DB
    # We follow the same pattern as get_or_create_sales_agent but forcing a new one
    q_insert = text("""
        INSERT INTO agents (name, role, tenant_id, config, model_provider, model_version, is_active, enabled_tools, system_prompt_template, template_type)
        VALUES (:name, :role, :tenant_id, :config :: jsonb, :provider, :version, :is_active, :tools :: jsonb, :prompt, :template_type)
        RETURNING id
    """)

    try:
        result = await db.execute(q_insert, {
            "name": final_config.get("agent_name", "Agente IA"),
            "role": "sales", # Default role for Hyper-Onboarding
            "tenant_id": tenant_id,
            "config": json.dumps(wizard_config),
            "provider": "openai",
            "version": "gpt-4o",
            "is_active": True,
            "tools": json.dumps(["search_specific_products", "search_by_category", "browse_general_storefront", "orders", "derivhumano"]), # Standard Suite
            "prompt": "Eres un asistente virtual de ventas.", # Pivot: Placeholder prompt to satisfy NotNull constraint. Wizard will overwrite.
            "template_type": "sales"
        })
        await db.commit()
        new_id = result.scalar()
        
        return {"agent_id": new_id, "status": "created"}
        
    except Exception as e:
        logger.error(f"Failed to create agent via Onboarding: {e}")
        raise HTTPException(status_code=500, detail=str(e))
@router.post("/draft")
async def onboarding_draft(
    tenant_id: int = Body(..., embed=True),
    final_config: dict = Body(..., embed=True),
    db: AsyncSession = Depends(get_db)
):
    """
    Saves the Architect's output as a DRAFT agent (is_active=False).
    Returns draft_id for the Wizard to hydrate.
    """
    from sqlalchemy import text
    import json
    
    # 1. Prepare Wizard Config
    wizard_config = {
        "store_name": final_config.get("agent_name", "Nuevo Agente (Borrador)"),
        "business_description": final_config.get("store_description", ""),
        "agent_tone": final_config.get("agent_tone", ""),
        "business_rules": final_config.get("business_rules", ""),
        "synonym_dictionary": final_config.get("synonym_dictionary", ""),
        "website_url": final_config.get("store_website", ""),
        "store_address": final_config.get("store_address", ""),
        "shipping_partners": final_config.get("shipping_partners", ""),
        "catalog_knowledge": final_config.get("catalog_knowledge", ""),
        "template_type": "sales",
    }

    # 2. Insert into DB as INACTIVE
    q_insert = text("""
        INSERT INTO agents (name, role, tenant_id, config, model_provider, model_version, is_active, enabled_tools, system_prompt_template, template_type)
        VALUES (:name, :role, :tenant_id, :config :: jsonb, :provider, :version, :is_active, :tools :: jsonb, :prompt, :template_type)
        RETURNING id
    """)

    try:
        result = await db.execute(q_insert, {
            "name": f"[DRAFT] {final_config.get('agent_name', 'Agente')}", 
            "role": "sales", 
            "tenant_id": tenant_id,
            "config": json.dumps(wizard_config),
            "provider": "openai",
            "version": "gpt-4o",
            "is_active": False, # <--- DRAFT MODE
            "tools": json.dumps(["search_specific_products", "search_by_category", "browse_general_storefront", "orders", "derivhumano"]),
            "prompt": "[DRAFT] Pendiente de generacion.", # Pivot: Placeholder for draft
            "template_type": "sales"
        })
        await db.commit()
        draft_id = result.scalar()
        
        return {"draft_id": draft_id, "status": "draft_saved"}
        
    except Exception as e:
        logger.error(f"Failed to save draft: {e}")
        raise HTTPException(status_code=500, detail=str(e))


# --- Wizard Interview Step (Section-Scoped Chat) ---

WIZARD_STEP_SESSIONS = {}

WIZARD_STEP_PROMPTS = {
    3: """Eres el Arquitecto de Tono del agente de IA. Tu mision es extraer la IDENTIDAD UNICA del negocio.

CHECKLIST INTERNO (no lo muestres al usuario, pero necesitas toda esta info):
- Nombre del negocio y que vende
- Que lo hace especial/diferente de la competencia
- Pronombres: vos / tu / usted
- Nivel de formalidad: casual / profesional / barrio
- Emojis: si/no, cuales
- Frases prohibidas o que deben evitarse
- Muletillas o frases puente del sector (ej: "Mira", "Fijate", "Dale")

ADAPTACION POR SECTOR:
- Ropa/moda: pregunta sobre estilos, temporadas, tallas
- Comida: pregunta sobre tipo de cocina, delivery, alergenos
- Tecnologia: pregunta sobre soporte tecnico, garantias
- Servicios: pregunta sobre turnos, reservas, presupuestos

ESTILO DE ENTREVISTA: Sos amigable y directo. Pregunta de a una cosa por vez. Usa ejemplos concretos: "Cuando entra un cliente a tu tienda, lo recibis con 'Hola, en que puedo ayudarte?' o con 'Ey! Que buscas?'"

Cuando tengas TODOS los items del checklist, genera un resumen estructurado y emiti:
<SECTION_COMPLETE>{"section": "tone", "draft": "## TONO Y PERSONALIDAD\\n..."}</SECTION_COMPLETE>""",

    4: """Eres el Arquitecto de Reglas del agente de IA. Tu mision es extraer las REGLAS OPERATIVAS del negocio.

CHECKLIST INTERNO:
- Politica de envios: gratis? desde que monto? zonas? tiempos?
- Politica de cambios/devoluciones: plazo, excepciones, condiciones
- Horarios de atencion: dias, franjas horarias, feriados
- Formas de pago: MercadoPago, tarjeta, transferencia, efectivo, cuotas
- Que cosas el agente NO debe hacer NUNCA
- Politica de precios: descuentos? negociacion? mayorista?
- Proceso de compra: como se cierra una venta?

ESTILO: Pregunta con escenarios reales: "Si un cliente pide devolver algo usado, que le decimos?" Convierte respuestas vagas en reglas concretas.

Cuando tengas TODO, genera reglas como imperativos claros y emiti:
<SECTION_COMPLETE>{"section": "rules", "draft": "## REGLAS DE NEGOCIO\\n1. ENVIOS: ...\\n2. CAMBIOS: ..."}</SECTION_COMPLETE>""",

    5: """Eres el Arquitecto de Diccionario del agente de IA. Tu mision es mapear el LENGUAJE REAL de los clientes.

CHECKLIST INTERNO:
- Sinonimos de categorias de productos (ej: "remera" = "playera" = "franela")
- Jerga del sector o region (argentinismos, mexicanismos, etc)
- Abreviaciones comunes que usan los clientes en WhatsApp
- Nombres alternativos de metodos de pago (ej: "Merca" = MercadoPago)
- Errores de ortografia frecuentes de los clientes

ESTILO: "Hay palabras que tus clientes usen mal o diferente? Por ejemplo, le dicen 'mallas' a los leotardos?"

Cuando tengas suficiente, genera tabla de sinonimos y emiti:
<SECTION_COMPLETE>{"section": "dictionary", "draft": "## DICCIONARIO DE SINONIMOS\\nCATEGORIA: sinonimo1, sinonimo2\\n..."}</SECTION_COMPLETE>"""
}


@router.post("/interview-step")
async def onboarding_interview_step(
    session_id: str = Body(..., embed=True),
    user_message: str = Body(..., embed=True),
    step: int = Body(..., embed=True),
    tenant_id: int = Body(0, embed=True),
    reset: bool = Body(False, embed=True),
):
    """
    Section-scoped interview for wizard steps 3, 4, 5.
    Each step uses a different prompt focused on that section.
    """
    if step not in WIZARD_STEP_PROMPTS:
        raise HTTPException(status_code=400, detail=f"Invalid step {step}. Must be 3, 4, or 5.")

    try:
        # Initialize or reset session
        step_session_key = f"{session_id}_step{step}"
        if reset or step_session_key not in WIZARD_STEP_SESSIONS:
            WIZARD_STEP_SESSIONS[step_session_key] = [
                {"role": "system", "content": WIZARD_STEP_PROMPTS[step]}
            ]
            if reset:
                user_message = "Hola, estoy listo para configurar esta seccion."

        # Append user message
        WIZARD_STEP_SESSIONS[step_session_key].append({"role": "user", "content": user_message})

        # Use platform API key (company pays for onboarding)
        api_key = os.getenv("OPENAI_API_KEY")
        if not api_key:
            raise HTTPException(status_code=500, detail="Platform API key not configured")

        client = openai.AsyncOpenAI(api_key=api_key)

        response = await client.chat.completions.create(
            model="gpt-4o",
            messages=WIZARD_STEP_SESSIONS[step_session_key],
            temperature=0.7
        )

        ai_text = response.choices[0].message.content
        WIZARD_STEP_SESSIONS[step_session_key].append({"role": "assistant", "content": ai_text})

        # Check for section completion
        import re
        section_complete = False
        extracted_draft = None

        pattern = re.compile(r"<SECTION_COMPLETE>(.*?)</SECTION_COMPLETE>", re.DOTALL | re.IGNORECASE)
        match = pattern.search(ai_text)

        if match:
            section_complete = True
            try:
                json_str = re.sub(r"```(?:json)?\n?|\n?```", "", match.group(1).strip()).strip()
                data = json.loads(json_str)
                extracted_draft = data.get("draft", "")
                ai_text = pattern.sub("", ai_text).strip()
            except Exception as e:
                logger.error(f"Section complete parse error: {e}")
                section_complete = False

        return {
            "ai_message": ai_text,
            "section_complete": section_complete,
            "extracted_draft": extracted_draft,
            "step": step
        }

    except Exception as e:
        logger.error(f"Interview step error: {e}")
        raise HTTPException(status_code=500, detail=str(e))
