import React, { useEffect, useState } from 'react';
import { useApi } from '../hooks/useApi';
import { Activity, MessageSquare } from 'lucide-react';
import { GlobalStreamLog } from '../components/GlobalStreamLog';
import { RagGalaxy } from '../components/RagGalaxy';
import { SystemStatus } from '../components/SystemStatus';

interface Stats {
    active_tenants: number;
    total_messages: number;
    processed_messages: number;
    roi_metrics: {
        total_gmv: number;
        conversions: number;
        last_30_days: number;
        formatted_gmv: string;
    };
}

interface HealthCheck {
    name: string;
    status: 'OK' | 'FAIL' | 'WARN';
    details?: string;
}

interface HealthData {
    status: string;
    checks: HealthCheck[];
}



export const Dashboard: React.FC = () => {
    const { fetchApi } = useApi();
    const [health, setHealth] = useState<HealthData>({ status: 'unknown', checks: [] });
    const [stats, setStats] = useState<Stats | null>(null);

    useEffect(() => {
        const loadDashboardData = async () => {
            try {
                const [healthData, statsData] = await Promise.all([
                    fetchApi('/admin/health'),
                    fetchApi('/admin/stats')
                ]);
                setHealth(healthData);
                setStats(statsData);
            } catch (err) {
                console.error("Failed to load dashboard telemetry:", err);
            }
        };
        loadDashboardData();
        // Poll every 30s
        const interval = setInterval(loadDashboardData, 30000);
        return () => clearInterval(interval);
    }, [fetchApi]);

    return (
        <div className="view active">
            <h1 className="view-title mb-6">Mission Control</h1>

            {/* CEO View: Value Generation (Hero Section) */}
            {stats?.roi_metrics && (
                <div className="mb-8">
                    <div className="glass p-8 rounded-2xl border border-emerald-500/20 bg-emerald-950/10 relative overflow-hidden">
                        <div className="absolute top-0 right-0 p-4 opacity-10">
                            <Activity size={120} />
                        </div>
                        <h2 className="text-sm font-bold text-emerald-400 tracking-wider mb-2">LAST 30 DAYS VALUE GENERATED</h2>
                        <div className="flex items-baseline gap-4">
                            <span className="text-6xl font-black text-white tracking-tight">
                                {stats.roi_metrics.formatted_gmv}
                            </span>
                            <span className="text-emerald-400 font-medium bg-emerald-500/10 px-3 py-1 rounded-full border border-emerald-500/20">
                                +{stats.roi_metrics.conversions} Conversions
                            </span>
                        </div>
                        <p className="text-white/40 mt-4 text-sm max-w-md">
                            Estimated revenue based on confirmed sales interactions and payment links generated by the AI agents.
                        </p>
                    </div>
                </div>
            )}

            {/* Operational Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
                {/* Traffic Stats */}
                <div className="stat-card glass">
                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span className="stat-label">Comms Traffic</span>
                        <MessageSquare className="stat-icon" size={20} color="var(--text-secondary)" />
                    </div>
                    <span className="stat-value">{stats?.total_messages || 0}</span>
                    <span className="stat-meta">Interactions Processed</span>
                </div>

                {/* Efficiency */}
                <div className="stat-card glass">
                    <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                        <span className="stat-label">Neural Efficiency</span>
                        <Activity className="stat-icon" size={20} color="var(--success)" />
                    </div>
                    <span className="stat-value">
                        {stats?.total_messages ? Math.round((stats.processed_messages / stats.total_messages) * 100) : 0}%
                    </span>
                    <span className="stat-meta">Operational Success Rate</span>
                </div>

                {/* System Status (Condensed) */}
                <div className="glass p-4 rounded-xl flex items-center justify-between">
                    <div>
                        <div className="text-xs text-white/40 uppercase font-bold tracking-wider">System Health</div>
                        <div className={`text-lg font-bold ${health.status === 'OK' ? 'text-green-400' : 'text-red-400'}`}>
                            {health.status}
                        </div>
                    </div>
                    <div className="h-2 w-2 rounded-full bg-green-500 animate-pulse" />
                </div>
            </div>

            {/* Phase 2: Global Neural Feed */}
            <GlobalStreamLog />

            {/* Secondary Technical Metrics */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mt-8 opacity-60 hover:opacity-100 transition-opacity">
                <SystemStatus health={health} />
                <RagGalaxy />
            </div>

        </div>
    );
};
